space_terms = [
    "Galaxy",
    "Nebula",
    "Star",
    "Planet",
    "Astronomy",
    "Cosmos",
    "Orbit",
    "Satellite",
    "Constellation",
    "Black Hole",
    "Supernova",
    "Comet",
    "Asteroid",
    "Meteoroid",
    "Celestial",
    "Universe",
    "Solar System",
    "Spacecraft",
    "Space Station",
    "Exoplanet",
    "Telescope",
    "Gravity",
    "Mars",
    "Jupiter",
    "Saturn",
    "Venus",
    "Mercury",
    "Uranus",
    "Neptune",
    "Pluto",
    "Interstellar",
    "Extraterrestrial",
    "Space Exploration",
    "Cosmonaut",
    "Astronaut",
    "Rocket",
    "Launch",
    "Lunar",
    "Lunar Module",
    "Space Shuttle",
    "Spacewalk",
    "Microgravity",
    "Space Probe",
    "Astrobiology",
    "Dark Matter",
    "Dark Energy",
    "Space-time",
    "Hubble Space Telescope",
    "Event Horizon",
    "Light-year",
    "Cosmic Rays",
    "Ecliptic",
    "Astrophysics",
    "Solar Wind",
    "Solar Flare",
    "Meteor Shower",
    "Gravitational Waves",
    "Space Debris",
    "Heliocentric",
    "Geocentric",
    "Red Giant",
    "White Dwarf",
    "Pulsar",
    "Astrolabe",
    "Galactic Center",
    "Outer Space",
    "Cosmogony",
    "Sputnik",
    "Big Bang",
    "Hubble's Law",
    "Event Horizon Telescope",
    "Space Race",
    "Celestial Mechanics",
    "Aurora",
    "Telemetry",
    "Zenith",
    "Nadir",
    "Zenithal Hourly Rate",
    "Rocket Science",
    "Escape Velocity",
    "Space Agency",
    "Astrochemistry",
    "Cryosphere",
    "Nuclear Fusion",
    "Ionosphere",
    "Celestial Navigation",
    "Astrodynamics",
    "Space Weather",
    "Observable universe",
    "Space-Time Continuum",
    "Astrogeology",
    "Astrograph",
    "Parallax",
    "Tidal Force",
    "Extravehicular Activity",
    "Lagrangian Points",
    "Quasar",
    "Galactic Halo",
    "Nucleosynthesis",
    "Celestial Sphere"
]

space_jokes = [
    "Why did the sun go to therapy? - It had too many issues!",
    "How does an astronaut cut his hair? - Eclipse it!",
    "What do you call an alien with three eyes? - An aliiien!",
    "Why didn't the sun go to college? - It already had a million degrees!",
    "What's an astronaut's favorite key on the keyboard? - The space bar!",
    "How do you organize a space party? - You planet!",
    "Why did the astronaut break up with his girlfriend? - He needed space!",
    "What did the black hole say to the other black hole? - 'You complete me.'",
    "Why did the comet break up with the moon? - It felt it needed space!",
    "What's a light astronaut's favorite drink? - Sprite!",
    "How do you throw a space party? - You planet!",
    "Why did the astronaut break up with his computer? - It had too many space issues!",
    "What do you call a space detective? - An unidentified flying object investigator!",
    "How do you organize a fantastic space barbecue? - You planet well in advance!",
    "What's an astronaut's favorite part of a computer? - The space bar!",
    "Why did the astronaut break up with his telescope? - It couldn't see their future together!",
    "How do you throw a party on Mars? - You planet!",
    "Why did the alien bring a suitcase to the spaceship? - Because it wanted to pack lightly!",
    "What do you call cheese from the moon? - Brie-lunar!",
    "Why was the math book sad in space? - Because it had too many problems!",
    "What's an astronaut's favorite chocolate? - Mars bars!",
    "Why don't astronauts use social media? - Because they need space!",
    "What did the astronaut use to keep his pants up? - An asteroid belt!",
    "Why did the astronaut break up with his astronaut girlfriend? - It was just a phase!",
    "How do you throw a space party? - You planet!",
    "What's an astronaut's favorite day of the week? - Moonday!",
    "Why did the astronaut break up with his comet girlfriend? - It was a short-term relationship!",
    "What do you call a spaceship that sings? - A celestial choir!",
    "Why did the astronaut break up with the alien? - It needed space!",
    "What did the alien say to the garden? - 'Take me to your weeder!'"
]

space_quotes = [
    "To confine our attention to terrestrial matters would be to limit the human spirit. - Stephen Hawking",
    "The important achievement of Apollo was demonstrating that humanity is not forever chained to this planet and our visions go rather further than that and our opportunities are unlimited. - Neil Armstrong",
    "Exploration knows no bounds, and we will not be bound by terrestrial limits. - Edwin 'Buzz' Aldrin",
    "Somewhere, something incredible is waiting to be known. - Carl Sagan",
    "Space exploration is a force of nature unto itself that no other force in society can rival. - Neil deGrasse Tyson",
    "Space exploration is a grand adventure pursued for the benefit of all humankind. - Michael Griffin",
    "Exploration is really the essence of the human spirit. - Frank Borman",
    "The universe is under no obligation to make sense to you. - Neil deGrasse Tyson",
    "The cosmos is within us. We are made of star-stuff. We are a way for the universe to know itself. - Carl Sagan",
    "I find it elevating and exhilarating to discover that we live in a universe which permits the evolution of molecular machines as intricate and subtle as we. - Carl Sagan",
    "The universe is a vast, unexplored canvas, waiting for us to paint our journey among the stars. - Unknown",
    "Every planet we reach is lifeless. - Gorillaz",
    "Space exploration is a journey of the human spirit. - Yuri Milner",
    "The most exciting phrase to hear in science is not 'Eureka!' but 'That's funny...' - Isaac Asimov",
    "Earth is the cradle of humanity, but mankind cannot stay in the cradle forever. - Konstantin Tsiolkovsky",
    "Dream beyond our limits, for in the vastness of space, we discover ourselves. - Unknown",
    "The beauty of space is that it inspires us to dream beyond our limits. - Unknown",
    "Space exploration will be the greatest adventure that humanity ever sets for itself. - Unknown",
    "The exploration of space will go ahead, whether we join in it or not. - John F. Kennedy",
    "We are all in the gutter, but some of us are looking at the stars. - Oscar Wilde",
    "We are an impossibility in an impossible universe. - Ray Bradbury",
    "The journey of a thousand miles begins with a single step. - Lao Tzu",
    "We are made of star-stuff. - Carl Sagan",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "The stars are the land-marks of the universe. - Sir John Frederick William Herschel",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Exploration is not just a choice we make; it is a necessity imposed upon us by the sheer size of the universe. - Carl Sagan",
    "The only way of discovering the limits of the possible is to venture a little way past them into the impossible. - Arthur C. Clarke",
    "Exploration knows no bounds, and the curiosity of man is limitless. - Unknown",
    "The universe is not required to be in perfect harmony with human ambition. - Carl Sagan"
]
